source 'https://rubygems.org'

gem 'jekyll', '~> 3.4'
gem "github-pages", group: :jekyll_plugins
gem 'wdm', '~> 0.1', :install_if => Gem.win_platform?
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw]